// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// clang-format off
// source: cls_logs.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30007
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30007 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Log;
@class LogGroup;
@class LogTag;
@class Log_Content;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ClsLogsRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface ClsLogsRoot : GPBRootObject
@end

#pragma mark - Log

typedef GPB_ENUM(Log_FieldNumber) {
  Log_FieldNumber_Time = 1,
  Log_FieldNumber_ContentsArray = 2,
};

GPB_FINAL @interface Log : GPBMessage

/** 时间戳，UNIX时间格式 */
@property(nonatomic, readwrite) int64_t time;
@property(nonatomic, readwrite) BOOL hasTime;

/** 一条日志里的多个kv组合 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Log_Content*> *contentsArray;
/** The number of items in @c contentsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger contentsArray_Count;

@end

#pragma mark - Log_Content

typedef GPB_ENUM(Log_Content_FieldNumber) {
  Log_Content_FieldNumber_Key = 1,
  Log_Content_FieldNumber_Value = 2,
};

GPB_FINAL @interface Log_Content : GPBMessage

/** 每组字段的 key */
@property(nonatomic, readwrite, copy, null_resettable) NSString *key;
/** Test to see if @c key has been set. */
@property(nonatomic, readwrite) BOOL hasKey;

/** 每组字段的 value */
@property(nonatomic, readwrite, copy, null_resettable) NSString *value;
/** Test to see if @c value has been set. */
@property(nonatomic, readwrite) BOOL hasValue;

@end

#pragma mark - LogTag

typedef GPB_ENUM(LogTag_FieldNumber) {
  LogTag_FieldNumber_Key = 1,
  LogTag_FieldNumber_Value = 2,
};

GPB_FINAL @interface LogTag : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *key;
/** Test to see if @c key has been set. */
@property(nonatomic, readwrite) BOOL hasKey;

@property(nonatomic, readwrite, copy, null_resettable) NSString *value;
/** Test to see if @c value has been set. */
@property(nonatomic, readwrite) BOOL hasValue;

@end

#pragma mark - LogGroup

typedef GPB_ENUM(LogGroup_FieldNumber) {
  LogGroup_FieldNumber_LogsArray = 1,
  LogGroup_FieldNumber_ContextFlow = 2,
  LogGroup_FieldNumber_Filename = 3,
  LogGroup_FieldNumber_Source = 4,
  LogGroup_FieldNumber_LogTagsArray = 5,
};

GPB_FINAL @interface LogGroup : GPBMessage

/** 多条日志合成的日志数组 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Log*> *logsArray;
/** The number of items in @c logsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger logsArray_Count;

/** 目前暂无效用 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *contextFlow;
/** Test to see if @c contextFlow has been set. */
@property(nonatomic, readwrite) BOOL hasContextFlow;

/** 日志文件名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *filename;
/** Test to see if @c filename has been set. */
@property(nonatomic, readwrite) BOOL hasFilename;

/** 日志来源，一般使用机器IP */
@property(nonatomic, readwrite, copy, null_resettable) NSString *source;
/** Test to see if @c source has been set. */
@property(nonatomic, readwrite) BOOL hasSource;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<LogTag*> *logTagsArray;
/** The number of items in @c logTagsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger logTagsArray_Count;

@end

#pragma mark - LogGroupList

typedef GPB_ENUM(LogGroupList_FieldNumber) {
  LogGroupList_FieldNumber_LogGroupListArray = 1,
};

GPB_FINAL @interface LogGroupList : GPBMessage

/** 日志组列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<LogGroup*> *logGroupListArray;
/** The number of items in @c logGroupListArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger logGroupListArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
