/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: cls_logs.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "cls_logs.pb-c.h"
void cls__log__content__init(Cls__Log__Content *message)
{
  static Cls__Log__Content init_value = CLS__LOG__CONTENT__INIT;
  *message = init_value;
}
void cls__log__init(Cls__Log *message)
{
  static Cls__Log init_value = CLS__LOG__INIT;
  *message = init_value;
}
size_t cls__log__get_packed_size(const Cls__Log *message)
{
  assert(message->base.descriptor == &cls__log__descriptor);
  return protobuf_c_message_get_packed_size((const ProtobufCMessage *)(message));
}
size_t cls__log__pack(const Cls__Log *message,
                      uint8_t *out)
{
  assert(message->base.descriptor == &cls__log__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t cls__log__pack_to_buffer(const Cls__Log *message,
                                ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cls__log__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message, buffer);
}
Cls__Log *
cls__log__unpack(ProtobufCAllocator *allocator,
                 size_t len,
                 const uint8_t *data)
{
  return (Cls__Log *)
      protobuf_c_message_unpack(&cls__log__descriptor,
                                allocator, len, data);
}
void cls__log__free_unpacked(Cls__Log *message,
                             ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cls__log__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
void cls__log_tag__init(Cls__LogTag *message)
{
  static Cls__LogTag init_value = CLS__LOG_TAG__INIT;
  *message = init_value;
}
size_t cls__log_tag__get_packed_size(const Cls__LogTag *message)
{
  assert(message->base.descriptor == &cls__log_tag__descriptor);
  return protobuf_c_message_get_packed_size((const ProtobufCMessage *)(message));
}
size_t cls__log_tag__pack(const Cls__LogTag *message,
                          uint8_t *out)
{
  assert(message->base.descriptor == &cls__log_tag__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t cls__log_tag__pack_to_buffer(const Cls__LogTag *message,
                                    ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cls__log_tag__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message, buffer);
}
Cls__LogTag *
cls__log_tag__unpack(ProtobufCAllocator *allocator,
                     size_t len,
                     const uint8_t *data)
{
  return (Cls__LogTag *)
      protobuf_c_message_unpack(&cls__log_tag__descriptor,
                                allocator, len, data);
}
void cls__log_tag__free_unpacked(Cls__LogTag *message,
                                 ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cls__log_tag__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
void cls__log_group__init(Cls__LogGroup *message)
{
  static Cls__LogGroup init_value = CLS__LOG_GROUP__INIT;
  *message = init_value;
}
size_t cls__log_group__get_packed_size(const Cls__LogGroup *message)
{
  assert(message->base.descriptor == &cls__log_group__descriptor);
  return protobuf_c_message_get_packed_size((const ProtobufCMessage *)(message));
}
size_t cls__log_group__pack(const Cls__LogGroup *message,
                            uint8_t *out)
{
  assert(message->base.descriptor == &cls__log_group__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t cls__log_group__pack_to_buffer(const Cls__LogGroup *message,
                                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cls__log_group__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message, buffer);
}
Cls__LogGroup *
cls__log_group__unpack(ProtobufCAllocator *allocator,
                       size_t len,
                       const uint8_t *data)
{
  return (Cls__LogGroup *)
      protobuf_c_message_unpack(&cls__log_group__descriptor,
                                allocator, len, data);
}
void cls__log_group__free_unpacked(Cls__LogGroup *message,
                                   ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cls__log_group__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
void cls__log_group_list__init(Cls__LogGroupList *message)
{
  static Cls__LogGroupList init_value = CLS__LOG_GROUP_LIST__INIT;
  *message = init_value;
}
size_t cls__log_group_list__get_packed_size(const Cls__LogGroupList *message)
{
  assert(message->base.descriptor == &cls__log_group_list__descriptor);
  return protobuf_c_message_get_packed_size((const ProtobufCMessage *)(message));
}
size_t cls__log_group_list__pack(const Cls__LogGroupList *message,
                                 uint8_t *out)
{
  assert(message->base.descriptor == &cls__log_group_list__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t cls__log_group_list__pack_to_buffer(const Cls__LogGroupList *message,
                                           ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cls__log_group_list__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message, buffer);
}
Cls__LogGroupList *
cls__log_group_list__unpack(ProtobufCAllocator *allocator,
                            size_t len,
                            const uint8_t *data)
{
  return (Cls__LogGroupList *)
      protobuf_c_message_unpack(&cls__log_group_list__descriptor,
                                allocator, len, data);
}
void cls__log_group_list__free_unpacked(Cls__LogGroupList *message,
                                        ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cls__log_group_list__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
static const ProtobufCFieldDescriptor cls__log__content__field_descriptors[2] =
    {
        {
            "key",
            1,
            PROTOBUF_C_LABEL_REQUIRED,
            PROTOBUF_C_TYPE_STRING,
            0, /* quantifier_offset */
            offsetof(Cls__Log__Content, key),
            NULL,
            NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "value",
            2,
            PROTOBUF_C_LABEL_REQUIRED,
            PROTOBUF_C_TYPE_STRING,
            0, /* quantifier_offset */
            offsetof(Cls__Log__Content, value),
            NULL,
            NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
};
static const unsigned cls__log__content__field_indices_by_name[] = {
    0, /* field[0] = key */
    1, /* field[1] = value */
};
static const ProtobufCIntRange cls__log__content__number_ranges[1 + 1] =
    {
        {1, 0},
        {0, 2}};
const ProtobufCMessageDescriptor cls__log__content__descriptor =
    {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "cls.Log.Content",
        "Content",
        "Cls__Log__Content",
        "cls",
        sizeof(Cls__Log__Content),
        2,
        cls__log__content__field_descriptors,
        cls__log__content__field_indices_by_name,
        1, cls__log__content__number_ranges,
        (ProtobufCMessageInit)cls__log__content__init,
        NULL, NULL, NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor cls__log__field_descriptors[2] =
    {
        {
            "time",
            1,
            PROTOBUF_C_LABEL_REQUIRED,
            PROTOBUF_C_TYPE_INT64,
            0, /* quantifier_offset */
            offsetof(Cls__Log, time),
            NULL,
            NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "contents",
            2,
            PROTOBUF_C_LABEL_REPEATED,
            PROTOBUF_C_TYPE_MESSAGE,
            offsetof(Cls__Log, n_contents),
            offsetof(Cls__Log, contents),
            &cls__log__content__descriptor,
            NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
};
static const unsigned cls__log__field_indices_by_name[] = {
    1, /* field[1] = contents */
    0, /* field[0] = time */
};
static const ProtobufCIntRange cls__log__number_ranges[1 + 1] =
    {
        {1, 0},
        {0, 2}};
const ProtobufCMessageDescriptor cls__log__descriptor =
    {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "cls.Log",
        "Log",
        "Cls__Log",
        "cls",
        sizeof(Cls__Log),
        2,
        cls__log__field_descriptors,
        cls__log__field_indices_by_name,
        1, cls__log__number_ranges,
        (ProtobufCMessageInit)cls__log__init,
        NULL, NULL, NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor cls__log_tag__field_descriptors[2] =
    {
        {
            "key",
            1,
            PROTOBUF_C_LABEL_REQUIRED,
            PROTOBUF_C_TYPE_STRING,
            0, /* quantifier_offset */
            offsetof(Cls__LogTag, key),
            NULL,
            NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "value",
            2,
            PROTOBUF_C_LABEL_REQUIRED,
            PROTOBUF_C_TYPE_STRING,
            0, /* quantifier_offset */
            offsetof(Cls__LogTag, value),
            NULL,
            NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
};
static const unsigned cls__log_tag__field_indices_by_name[] = {
    0, /* field[0] = key */
    1, /* field[1] = value */
};
static const ProtobufCIntRange cls__log_tag__number_ranges[1 + 1] =
    {
        {1, 0},
        {0, 2}};
const ProtobufCMessageDescriptor cls__log_tag__descriptor =
    {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "cls.LogTag",
        "LogTag",
        "Cls__LogTag",
        "cls",
        sizeof(Cls__LogTag),
        2,
        cls__log_tag__field_descriptors,
        cls__log_tag__field_indices_by_name,
        1, cls__log_tag__number_ranges,
        (ProtobufCMessageInit)cls__log_tag__init,
        NULL, NULL, NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor cls__log_group__field_descriptors[5] =
    {
        {
            "logs",
            1,
            PROTOBUF_C_LABEL_REPEATED,
            PROTOBUF_C_TYPE_MESSAGE,
            offsetof(Cls__LogGroup, logs_count),
            offsetof(Cls__LogGroup, logs),
            &cls__log__descriptor,
            NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "contextFlow",
            2,
            PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_STRING,
            0, /* quantifier_offset */
            offsetof(Cls__LogGroup, contextflow),
            NULL,
            NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "filename",
            3,
            PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_STRING,
            0, /* quantifier_offset */
            offsetof(Cls__LogGroup, filename),
            NULL,
            NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "source",
            4,
            PROTOBUF_C_LABEL_OPTIONAL,
            PROTOBUF_C_TYPE_STRING,
            0, /* quantifier_offset */
            offsetof(Cls__LogGroup, source),
            NULL,
            NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
        {
            "logTags",
            5,
            PROTOBUF_C_LABEL_REPEATED,
            PROTOBUF_C_TYPE_MESSAGE,
            offsetof(Cls__LogGroup, n_logtags),
            offsetof(Cls__LogGroup, logtags),
            &cls__log_tag__descriptor,
            NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
};
static const unsigned cls__log_group__field_indices_by_name[] = {
    1, /* field[1] = contextFlow */
    2, /* field[2] = filename */
    4, /* field[4] = logTags */
    0, /* field[0] = logs */
    3, /* field[3] = source */
};
static const ProtobufCIntRange cls__log_group__number_ranges[1 + 1] =
    {
        {1, 0},
        {0, 5}};
const ProtobufCMessageDescriptor cls__log_group__descriptor =
    {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "cls.LogGroup",
        "LogGroup",
        "Cls__LogGroup",
        "cls",
        sizeof(Cls__LogGroup),
        5,
        cls__log_group__field_descriptors,
        cls__log_group__field_indices_by_name,
        1, cls__log_group__number_ranges,
        (ProtobufCMessageInit)cls__log_group__init,
        NULL, NULL, NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor cls__log_group_list__field_descriptors[1] =
    {
        {
            "logGroupList",
            1,
            PROTOBUF_C_LABEL_REPEATED,
            PROTOBUF_C_TYPE_MESSAGE,
            offsetof(Cls__LogGroupList, n_loggrouplist),
            offsetof(Cls__LogGroupList, loggrouplist),
            &cls__log_group__descriptor,
            NULL,
            0,            /* flags */
            0, NULL, NULL /* reserved1,reserved2, etc */
        },
};
static const unsigned cls__log_group_list__field_indices_by_name[] = {
    0, /* field[0] = logGroupList */
};
static const ProtobufCIntRange cls__log_group_list__number_ranges[1 + 1] =
    {
        {1, 0},
        {0, 1}};
const ProtobufCMessageDescriptor cls__log_group_list__descriptor =
    {
        PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
        "cls.LogGroupList",
        "LogGroupList",
        "Cls__LogGroupList",
        "cls",
        sizeof(Cls__LogGroupList),
        1,
        cls__log_group_list__field_descriptors,
        cls__log_group_list__field_indices_by_name,
        1, cls__log_group_list__number_ranges,
        (ProtobufCMessageInit)cls__log_group_list__init,
        NULL, NULL, NULL /* reserved[123] */
};
