# 1. 统一工程最低部署版本（匹配Xcode 15+，避免版本冲突）
platform :ios, '12.0'

target 'TencentCloudLogDemo' do
  use_frameworks! # 动态库模式（必须保留，适配TencentCloudLogProducer）
  pod 'TencentCloudLogProducer/Core', :path => '../../'
  pod 'TencentCloudLogProducer/NetWorkDiagnosis', :path => '../../'

  # 3. 测试Target：TencentCloudLogDemoTests（单元测试）
  target 'TencentCloudLogDemoTests' do
    inherit! :search_paths
    pod 'OCMock', '~> 3.0' # 
  end
#
#  target 'TencentCloudLogDemoUITests' do
#    inherit! :search_paths
#  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # 修复 Protobuf 部署目标版本警告
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      
      # 禁用测试 target 的 sandbox（修复权限问题）
      if target.name.include?('Tests')
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      end
    end
  end
end
