# 1. 统一工程最低部署版本（匹配Xcode 15+，避免版本冲突）
platform :ios, '10.0'

target 'TencentCloudLogDemo' do
  # use_frameworks! # 动态库模式（必须保留，适配TencentCloudLogProducer）
  pod 'TencentCloudLogProducer/Core', :path => '../../'
  pod 'TencentCloudLogProducer/NetWorkDiagnosis', :path => '../../'

  # 3. 测试Target：TencentCloudLogDemoTests（单元测试）
  target 'TencentCloudLogDemoTests' do
    inherit! :search_paths
    pod 'OCMock', '~> 3.0' # 
  end
#
#  target 'TencentCloudLogDemoUITests' do
#    inherit! :search_paths
#  end
end
